GET http://localhost:3004/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTmFydXRvIiwiaWF0IjoxNjAyNzQyMzI3fQ._kqCEaEQUJR_X0gcblaGq0vHd16WAmIg4O0MmDSqZWk

###

POST http://localhost:3004/login
Content-Type: application/json

{
    "username": "Naruto"
}